version: '2.4'

services:

  nginx:
    image: "grocy/nginx:${GROCY_VERSION?GROCY_VERSION}${RELEASE_SUFFIX:--rc0}"
    build:
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '80:8080'
      - '443:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
      - www-public:/var/www/public:ro
    container_name: nginx

  grocy:
    image: "grocy/grocy:${GROCY_VERSION?GROCY_VERSION}${RELEASE_SUFFIX:--rc0}"
    build:
      args:
        GITHUB_API_TOKEN: "${GITHUB_API_TOKEN}"
        GROCY_VERSION: "${GROCY_VERSION}"
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - database:/var/www/data
      - www-public:/var/www/public:ro
    env_file:
      - grocy.env
    container_name: grocy

volumes:
  database:
  www-public:
