version: '2.4'

services:
  grocy-nginx:
    image: grocy/grocy-docker:nginx
    build:
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '80:8080'
      - '443:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
      - www-public:/var/www/public:ro
    container_name: grocy-nginx

  grocy:
    image: grocy/grocy-docker:grocy
    build:
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - database:/var/www/data
      - www-public:/var/www/public
    env_file:
      - grocy.env
    container_name: grocy
volumes:
  database:
  www-public:
