apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grocy
  name: grocy
spec:
  containers:
  - image: localhost/grocy-nginx
    ports:
    - containerPort: 80
      hostPort: 8000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  - command:
    - php-fpm
    env:
    - name: GROCY_CULTURE
      value: en
    - name: MAX_UPLOAD
      value: 50M
    - name: PHP_MAX_FILE_UPLOAD
      value: 200
    - name: PHP_MAX_POST
      value: 100M
    - name: PHP_MEMORY_LIMIT
      value: 512M
    image: localhost/grocy-app
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: true
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs-tmp
    - mountPath: /var/tmp
      name: tmpfs-var-tmp
    - mountPath: /run
      name: tmpfs-run
    workingDir: /www/public
  volumes:
  # TODO: Remove: this effectively performs 'mkdir /tmp/grocy'
  - hostPath:
      path: /tmp/grocy
      type: DirectoryOrCreate
    name: tmpfs
  - hostPath:
      path: /tmp/grocy/tmp
      type: DirectoryOrCreate
    name: tmpfs-tmp
  # TODO: Remove: this effectively performs 'mkdir /tmp/grocy/var'
  - hostPath:
      path: /tmp/grocy/var
      type: DirectoryOrCreate
    name: tmpfs-var
  - hostPath:
      path: /tmp/grocy/var/tmp
      type: DirectoryOrCreate
    name: tmpfs-var-tmp
  - hostPath:
      path: /tmp/grocy/run
      type: DirectoryOrCreate
    name: tmpfs-run
status: {}
