apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grocy
  name: grocy
spec:
  containers:
  - image: localhost/grocy-nginx:libpod-issue-5631
    ports:
    - containerPort: 80
      hostPort: 8000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  - command:
    - php-fpm
    env:
    - name: GROCY_CULTURE
      value: en
    - name: MAX_UPLOAD
      value: 50M
    - name: PHP_MAX_FILE_UPLOAD
      value: 200
    - name: PHP_MAX_POST
      value: 100M
    - name: PHP_MEMORY_LIMIT
      value: 512M
    image: localhost/grocy-app:libpod-issue-5631
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: true
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    - mountPath: /var/tmp
      name: tmpfs
    - mountPath: /run
      name: tmpfs
    workingDir: /www/public
  volumes:
  - hostPath:
      path: tmpfs
      type: DirectoryOrCreate
    name: tmpfs
status: {}
